routes.py
# coding=utf-8
import udatetime
from aucr_app import db
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, send_from_directory, g
from flask_login import login_required, current_user
from aucr_app.plugins.auth.models import Groups, Group
from aucr_app.plugins.unum.forms import UploadFile, EditUploadFile, Unum, UNUMSearchForm
from aucr_app.plugins.unum.unum_globals import CLASSIFICATION_AVAILABLE_CHOICES
from aucr_app.plugins.unum.models import UNUM, Classification
from aucr_app.plugins.analysis.routes import get_upload_file_hash
from aucr_app.plugins.analysis.file.upload import allowed_file
from aucr_app.plugins.analysis.file.zip import encrypt_zip_file
from werkzeug.utils import secure_filename
from flask_babel import get_locale

unum = Blueprint('unum', __name__, template_folder='templates')


@unum.before_app_request
def before_request():
    """Set user last seen time user."""
    if current_user.is_authenticated:
        g.unum_search_form = UNUMSearchForm()
    g.locale = str(get_locale())


@unum.route('/search')
@login_required
def unum_search():
    """UNUM search plugin flask blueprint."""
    page = request.args.get('page', 1, type=int) or 1
    posts, total = UNUM.search(g.unum_search_form.q.data, page, int(current_app.config['POSTS_PER_PAGE']))
    search_uploaded_files, total = \
        UNUM.search(g.unum_search_form.q.data, page, int(current_app.config['POSTS_PER_PAGE']))
    next_url = url_for('unum.unum_search', q=g.unum_search_form.q.data, page=page + 1) \
        if total["value"] > page * int(current_app.config['POSTS_PER_PAGE']) else None
    prev_url = url_for('unum.unum_search', q=g.unum_search_form.q.data, page=page - 1) if page > 1 else None
    return render_template('unum_search.html', title='UNUM Search', page=page, search_url='unum.unum_search',
                           next_url=next_url, prev_url=prev_url, posts=posts, file_results=search_uploaded_files)


@unum.route('/unum_file_download/<path:md5_hash>')
@login_required
def unum_file_download(md5_hash):
    """File Download web call."""
    _id = UNUM.query.filter_by(md5_hash=md5_hash).first()
    group_access_value = Group.query.filter_by(username_id=current_user.id, groups_id=_id.group_access).first()
    if group_access_value:
        file_upload_path = current_app.config['FILE_FOLDER']
        if file_upload_path[:-1] != "/":
            file_upload_path += "/"
        encrypt_zip_file("infected", str(md5_hash + ".zip"), [f"{file_upload_path}{md5_hash}"])
        return send_from_directory(current_app.config['TMP_FILE_FOLDER'], str(md5_hash + ".zip"), as_attachment=True)


@unum.route('/unum', methods=['GET', 'POST'])
@login_required
def unum_plugin_route():
    """the tasks function returns the plugin framework for the unum default task view"""
    # TODO show current unum in the database
    if request.method == 'POST':
        return redirect("/unum/create")
    form = Unum(request.form)
    classification_choices = []
    for items in Classification.query.all():
        classification_choices.append((int(items.id), items.classification))
    page = request.args.get('page', 1, type=int) or 1
    count = page * 10
    upload_dict = {}
    total = 0
    while total < 10:
        total += 1
        id_item = count - 10 + total
        item = UNUM.query.filter_by(id=id_item).first()
        if item:
            group_ids = Group.query.filter_by(username_id=current_user.id).all()
            for group_items in group_ids:
                if item.group_access == group_items.groups_id:
                    if len(item.file_name) >= 32:
                        table_file_name_formatted = str(item.file_name[:26] + "..." + item.file_name[-8:])
                    else:
                        table_file_name_formatted = item.file_name
                    classification_value = Classification.query.filter_by(id=item.classification).first()
                    item_dict = {"id": item.id, "description": item.description, "md5_hash": item.md5_hash,
                                 "file_name": table_file_name_formatted,
                                 "classification": classification_value.classification}
                    upload_dict[str(item.id)] = item_dict
    prev_url = '?page=' + str(page - 1)
    next_url = '?page=' + str(page + 1)
    return render_template('unum.html', title='Unum Search', page=page, table_dict=upload_dict,
                           form=form, search_url='unum.unum_search', next_url=next_url, prev_url=prev_url)


@unum.route('/create', methods=['GET', 'POST'])
@login_required
def unum_file_route():
    """Create upload default view."""
    group_info = Groups.query.all()
    classification_choices_list = Classification.query.all()
    classification_choices = []
    assigned_classification_value = None
    for items in Classification.query.all():
        classification_choices.append((int(items.id), items.classification))
    if request.method == 'POST':
        form = UploadFile(request.form)
        md5_hash = None
        if form.validate_on_submit():
            form.classification.choices = classification_choices
            try:
                file = request.files['file']
            except KeyError:
                file = None
            if file and allowed_file(file.filename):
                secure_filename(file.filename)
                md5_hash = get_upload_file_hash(file)
            duplicate_file = UNUM.query.filter_by(md5_hash=md5_hash).first()
            classification_choices = classification_choices_list
            if duplicate_file:
                flash("The upload file has already been uploaded.")
                return redirect(url_for('unum.unum_plugin_route'))
            new_upload = UNUM(description=form.description.data,
                              created_by=current_user.id,
                              classification=form.classification.data[0],
                              file_name=str(file.filename),
                              group_access=form.group_access.data[0],
                              created_time_stamp=udatetime.utcnow(),
                              modify_time_stamp=udatetime.utcnow(),
                              md5_hash=md5_hash)
            db.session.add(new_upload)
            db.session.commit()
            flash("The upload file has been created and we started processing it for you.")
            return redirect(url_for('unum.unum_plugin_route'))
        else:
            for error in form.errors:
                flash(str(form.errors[error][0]), 'error')
            return redirect(url_for('unum.unum_plugin_route'))
    form = UploadFile(request.form)
    form.classification.choices = classification_choices
    return render_template('unum_upload_file.html',
                           title='Upload New File',
                           form=form,
                           groups=group_info,
                           classification=classification_choices)


@unum.route('/edit', methods=['GET', 'POST'])
@login_required
def edit_upload_file_route():
    """Edit Uploaded File view."""
    group_info = Groups.query.all()
    submitted_upload_id = request.args.get("id")
    upload = UNUM.query.filter_by(id=submitted_upload_id).first()
    test = request.args.get("groups_access")
    try:
        group_id = int(request.form["groups_access"])
    except:
        try:
            group_id = int(request.form["groups_access"])
        except:
            group_id = upload.group_access
    group_access_value = Group.query.filter_by(username_id=current_user.id, groups_id=group_id).first()
    if group_access_value:
        group_ids = Group.query.filter_by(username_id=current_user.id).all()
        user_groups = []
        for user_group in group_ids:
            user_groups.append(user_group.groups_id)
        group_choices = []
        for group in Groups.query.all():
            group_choices.append((int(group.id), group.name))
        if request.method == 'POST':
            if upload:
                form = EditUploadFile(request.form)
                if form.validate_on_submit():
                    if upload is not None:
                        upload.description = request.form["description"]
                        upload.classification = int(request.form["classification"])
                        upload.group_access = int(request.form["groups_access"])
                        db.session.commit()
            return redirect(url_for('unum.unum_plugin_route'))
        if request.method == "GET":
            if upload:
                form = EditUploadFile(upload)
                assigned_group_value = None
                classification_choices_list = Classification.query.all()
                classification_choices = []
                assigned_classification_value = None
                for items in Classification.query.all():
                    classification_choices.append((int(items.id), items.classification))
                for items in group_choices:
                    if items[0] == upload.group_access:
                        assigned_group_value = items[1]
                for items in classification_choices:
                    if items[0] == upload.classification:
                        assigned_classification_value = items[1]
                table_dict = {"id": upload.id,
                              "description": upload.description,
                              "md5": upload.md5_hash,
                              "classification": assigned_classification_value,
                              "group_access": assigned_group_value}
                return render_template('edit_upload_file.html',
                                       title='Edit Upload File',
                                       form=form, groups=group_info,
                                       classification=classification_choices,
                                       table_dict=table_dict,

templates/_unum_files.html
<table class="table table-hover">
    <tr>
        <td>
            {{ _("File ID") }} : <a href="{{  url_for('unum.edit_upload_file_route', id=post.id) }}">{{ post.id }}</a>
        <br>
           {{ _("MD5") }}:
                <a href="{{  url_for('unum.unum_file_download', md5_hash=post.md5_hash) }}">{{ post.md5_hash }}</a>
        <br>
            {{ _("Description") }} : {{ post.description }}
        <br>
            {{ _("File Name") }} : {{ post.file_name }}
        </td>
    </tr>
</table>

templates/edit_upload_file.html
{% extends "base.html" %}


{% block app_content %}
    <main class="mdl-layout__content">
        <div class="mdl-layout-spacer"></div>
        <section class="section--center mdl-grid mdl-shadow--2dp">
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">{{ title }}</h2>
            </div>
            <div class="mdl-card__supporting-text">Upload ID: {{ form.upload_id }} MD5:
                <a href="{{  url_for('unum.unum_file_download', md5_hash=table_dict.md5) }}">{{ table_dict.md5 }}</a>
            </div>
            <div class="mdl-card__actions">
                <form class="form" method="post" role="form">
                    {{ form.hidden_tag() }}
                    {% with form_object=description, form_object_name="description", form_object_rows=1, form_object_label="Description", form_object_value=form.description %}
                        {% include "subtemplates/_form_object_textfield.html" %}
                    {% endwith %}
                    {% with iterable_thing=classification, dropdown_topic="classification", dropdown_label="Classification", form_object_value=form.data.classification, dropdown_topic_set="True" %}
                        {% include "subtemplates/_dropdown_list.html" %}
                    {% endwith %}
                    {% with iterable_thing=groups_access, dropdown_topic="groups_access", dropdown_label="Group Access", form_object_value=form.group_access,  dropdown_topic_set="True" %}
                        {% include "subtemplates/_dropdown_list.html" %}
                    {% endwith %}
                    <div class="mdl-layout-spacer"></div>
                    <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
                            value=data-val.value>
                        Save
                    </button>
                </form>
            </div>
        </section>
        <div class="mdl-layout-spacer"></div>
    </main>
    <div class="mdl-layout-spacer"></div>
{% endblock %}

templates/unum.html
{% extends "base.html" %}


{% block app_content %}
    <main class="mdl-layout__content">
        <div class="mdl-grid">
            <div class="page-content">
                    <div class="mdl-grid">
                <span class="mdl-layout-title">Unum</span>
                <div class="mdl-layout-spacer"></div>
                <form class="form" method="post" role="form">
                        {{ form.hidden_tag() }}
                        <!--</div>-->
                {% with form_object="uploadbutton", button_text="",button_icon="add", button_value="createnewcasebutton" %}
                    {% include "subtemplates/_plain_button.html" %}
                {% endwith %}
                </form>
            </div>
            <div class="mdl-layout-spacer"></div>
                {% with form_object="table",
                    checkbox_enabled="True",
                    table_list=[],
                    table_data=table_dict,
                    table_header=["Upload File ID", "Description", "MD5", "File_Name", "Classification"],
                    url_for_value='unum.edit_upload_file_route'  %}
                {% include "subtemplates/_table_object.html" %}
            {% endwith %}
            {% with form_object="prevnextnav", prev_url=prev_url, prev_text="Back", next_url=next_url, next_text="Next" %}
                {% include "subtemplates/_prev_next_nav.html" %}
            {% endwith %}
            <div class="mdl-layout-spacer"></div>
            </div>
        </div>
    </main>
{% endblock %}

templates/unum_search.html
{% extends "base.html" %}


{% block app_content %}
    <h3>{{ _('UNUM File Search Results') }}</h3>
    {% for post in file_results %}
        {% include '_unum_files.html' %}
    {% endfor %}
    {% if messages %}
        <nav aria-label="...">
            <ul class="pager">
                {% with form_object="prevnextnav", prev_url=prev_url, prev_text="New Files", next_url=next_url,
                    next_text="Old Files" %}
                    {% include "subtemplates/_prev_next_nav.html" %}
                {% endwith %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

templates/unum_upload_file.html
{% extends "base.html" %}


{% block app_content %}
    <style>
        .demo-list-action {
          width: 600px;
        }
        .mdl-textfield{
          width:1000px;
        }
    </style>
    <main class="mdl-layout__content">
        <div class="mdl-layout-spacer"></div>
        <div class = "mdl-tabs mdl-js-tabs">
            <div class = "mdl-tabs__tab-bar">
                 <a href="#file-submission" class="mdl-tabs__tab is-active">File</a>
                 <a href="#url-submission" class="mdl-tabs__tab">URL</a>
                 <a href="#hash-submission" class="mdl-tabs__tab">Hash</a>
            </div>
            <div class="mdl-tabs__panel is-active" id="file-submission">
                <div class="mdl-grid">
                    <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
                        <div class="mdl-card__title">
                            <h2 class="mdl-card__title-text">{{ title }}</h2>
                        </div>
                        <div class="mdl-card__supporting-text">{{ supporting_text }}
                        </div>
                        <div class="mdl-card__actions mdl-card--border ">
                            <form class="form" method="post" role="form" enctype="multipart/form-data">
                               {{ form.hidden_tag() }}

                                {% with form_object=description, form_object_name="description", form_object_rows=1, form_object_label="Description", form_object_value=form.data.description  if form.data.description != None else ""%}
                                    {% include "subtemplates/_form_object_textfield.html" %}
                                {% endwith %}
                                <div class="mdl-layout-spacer"></div>
                                {% include "upload_file.html" %}
                                <div class="mdl-layout-spacer"></div>
                                {% with iterable_thing=classification, dropdown_topic="classification", dropdown_label="Classification", form_object_value=form.data.classification, dropdown_topic_set="True" %}
                                    {% include "subtemplates/_dropdown_list.html" %}
                                {% endwith %}
                                {% with iterable_thing=groups, dropdown_topic="group_access", dropdown_label="Group Access", form_object_value=form.data.group_access  %}
                                    {% include "subtemplates/_dropdown_object.html" %}
                                {% endwith %}
                                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
                                        value=data-val.value>
                                    Create
                                </button>
                            </form>
                        </div>
                    </section>
                </div>
            </div>
            <div class="mdl-tabs__panel" id="url-submission">
                <div class="mdl-grid">
                    <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
                        <div class="mdl-card__title">
                            <h2 class="mdl-card__title-text">{{ title }}</h2>
                        </div>
                        <div class="mdl-card__supporting-text">{{ supporting_text }}
                        </div>
                        <div class="mdl-card__actions mdl-card--border ">
                            <form class="form" method="post" role="form" enctype="multipart/form-data">
                               {{ form.hidden_tag() }}

                                {% with form_object=description, form_object_name="description", form_object_rows=1, form_object_label="Description", form_object_value=form.data.description  if form.data.description != None else ""%}
                                    {% include "subtemplates/_form_object_textfield.html" %}
                                {% endwith %}
                                {% with form_object=submit_url, form_object_name="submit_url", form_object_rows=1, form_object_label="URL", form_object_value=form.data.submit_url  if form.data.submit_url != None else ""%}
                                    {% include "subtemplates/_form_object_textfield.html" %}
                                {% endwith %}
                                <div class="mdl-layout-spacer"></div>
                                {% with iterable_thing=classification, dropdown_topic="classification", dropdown_label="Classification", form_object_value=form.data.classification %}
                                    {% include "subtemplates/_dropdown_list.html" %}
                                {% endwith %}
                                {% with iterable_thing=groups, dropdown_topic="group_access", dropdown_label="Group Access",form_object_value=form.data.group_access %}
                                    {% include "subtemplates/_dropdown_object.html" %}
                                {% endwith %}
                                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
                                        value=data-val.value>
                                    Create
                                </button>
                            </form>
                        </div>
                    </section>
                </div>
            </div>
            <div class="mdl-tabs__panel" id="hash-submission">
                <div class="mdl-grid">
                    <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
                        <div class="mdl-card__title">
                            <h2 class="mdl-card__title-text">{{ title }}</h2>
                        </div>
                        <div class="mdl-card__supporting-text">{{ supporting_text }}
                        </div>
                        <div class="mdl-card__actions mdl-card--border ">
                            <form class="form" method="post" role="form" enctype="multipart/form-data">
                               {{ form.hidden_tag() }}

                                {% with form_object=description, form_object_name="description", form_object_rows=1, form_object_label="Description", form_object_value=form.data.description  if form.data.description != None else ""%}
                                    {% include "subtemplates/_form_object_textfield.html" %}
                                {% endwith %}
                                {% with form_object=submit_hash, form_object_name="submit_hash", form_object_rows=1, form_object_label="Hash", form_object_value=form.data.submit_hash  if form.data.submit_hash != None else ""%}
                                    {% include "subtemplates/_form_object_textfield.html" %}
                                {% endwith %}
                                <div class="mdl-layout-spacer"></div>
                                {% with iterable_thing=classification, dropdown_topic="classification", dropdown_label="Classification", form_object_value=form.data.classification %}
                                    {% include "subtemplates/_dropdown_list.html" %}
                                {% endwith %}
                                {% with iterable_thing=groups, dropdown_topic="group_access", dropdown_label="Group Access",form_object_value=form.data.group_access %}
                                    {% include "subtemplates/_dropdown_object.html" %}
                                {% endwith %}
                                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
                                        value=data-val.value>
                                    Create
                                </button>
                            </form>
                        </div>
                    </section>
                </div>
            </div>
        </div>
        <div class="mdl-layout-spacer"></div>
    </main>
    <div class="mdl-layout-spacer"></div>
{% endblock %}